services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./docker/nginx/default-preview.conf:/etc/nginx/conf.d/default.conf:ro
      - app-public-data-${PR_ID:-local}:/var/www/public:ro
      - ./docker/nginx/.htpasswd:/etc/nginx/auth/.htpasswd:ro
    depends_on:
      - app
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"

  app:
    image: devc4rlos/testing-dev-flow:${IMAGE_TAG:-latest}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app-public-data-${PR_ID:-local}:/var/www/public
      - ./.env:/var/www/.env:ro
    env_file:
      - ./.env
    networks:
      - proxy
    healthcheck:
      test: [ "CMD-SHELL", "fpm-healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - proxy
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  app-public-data-${PR_ID:-local}:
  db-data:
    driver: local

networks:
  proxy:
    external: true
